apiVersion: apps/v1    # DEPLOYMENT
kind: Deployment
metadata:
  name: wordpress-deployment-app
  namespace: default


spec:    # POD WORDPRESS APP
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-pod-app
  template:
    metadata:
      labels:
        app: wordpress-pod-app

    spec: # CONTAINER
      containers:
      - name: app
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-app
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: "123"
        - name: WORDPRESS_DB_NAME
          value: "database-teste-cezar"
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst